### ISSUE TITLE
[BUG] Trying to get property 'deliveryAddress' of non-object

### ISSUE THREAD

**Issue by albundy2** [tig-nl/gls-magento2#9] opened 2020-11-30 13:54 UTC
**To Reproduce**
got to order
try to create shipping label

**Expected result**
creating a shipping label

**Actual result**
Describe the actual result
when trying to create a shipping label for a order i get this error:
{"0":"Notice: Trying to get property 'deliveryAddress' of non-object in \/var\/www\/vhosts\/shoes.nl\/httpdocs\/vendor\/tig\/gls-magento2\/Service\/Label\/Create.php on line 156","1":"#1 TIG\\GLS\\Service\\Label\\Create->mapLabelData(&Magento\\Sales\\Model\\Order\\Shipment\\Interceptor#000000003f3368ff0000000038859bdd#, 'TIG_GLS', 1.1)

**Workaround**
Describe the temporarily workaround or if none exists write "None"
no workarround

**Screenshots**

** Please complete the following information**
Magento 2.3.5p1
PHP  7.2.34
1.3.5

**Comment by tig-jaspersmits** [comment] 2020-11-30 14:41
Hi @albundy2 ,

Thanks for letting us know. I've just tried to reproduce this but nothing goes wrong when I try to create a label.
Seems like there is something not right with the delivery address. Is there anything strange you see when it comes to that? Is there a screenshot you could share maybe?

Kind regards,
Jasper
TIG

**Comment by albundy2** [comment] 2020-11-30 15:03
it's a address in Czech Republic, It has special characters but i have remove those and also put the address number on address lne 2 but the problem stays the same after retrying
![Untitled-4](https://user-images.githubusercontent.com/15823253/100626034-90bc5400-3325-11eb-8766-58b3277cbcc3.png)

**Comment by albundy2** [comment] 2020-11-30 15:08
is no longer need please delete the contact address information i have send in screenshot

**Comment by tig-jaspersmits** [comment] 2020-11-30 15:28
Hi @albundy2 ,

I've deleted the image. Tried to checkout with that and I was able to generate a label.
Probably something else going on here. I would recommend contacting GLS support about this and follow the regular support route when it comes to this problem.

Kind regards,
Jasper
TIG

**Comment by albundy2** [comment] 2020-12-02 21:27
Hi Jasper,

done this on monday no answer or reply. Can it be that there is a issue because i also use TIG PostNL module in the same website?

**Comment by tig-jaspersmits** [comment] 2020-12-03 08:25
Hi @albundy2 ,

I've tested this on my environment with both GLS and PostNL active. I did this because your previous case also concerned the two extensions being installed. Or were you only able to replicate this with both extensions active?

Kind regards,
Jasper
TIG

**Comment by albundy2** [comment] 2020-12-03 10:27
PostNL plugin is working without problems and it isn't making any differents if it is enable or not for the result of GLS create labels. I have removed the GLS Plugin on my staging website through composer upgrade, compile and deploy and then done a new install through composer but the result stays the same. The GLS plugin is working except creating labels given errors

**Comment by tig-jaspersmits** [comment] 2020-12-03 10:44
Hi @albundy2 ,

It might be better to handle this as an individual case. Because it doesn't seem like a core problem with the extension since I was unable to reproduce it. Could you contact us through support@tig.nl? We will look into it specifically for your environment. I'll close this one once you agree on try the solve the case like that.

Kind regards,
Jasper
TIG

**Comment by albundy2** [comment] 2020-12-03 11:11
That oke for me I will send you a e-mail on request e-mail address

Van: Jasper Smits <notifications@github.com>
Verzonden: donderdag 3 december 2020 11:44
Aan: tig-nl/gls-magento2 <gls-magento2@noreply.github.com>
CC: albundy2 <privatenl@msn.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [tig-nl/gls-magento2] [BUG] Trying to get property 'deliveryAddress' of non-object (#9)


Hi @albundy2<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Falbundy2&data=04%7C01%7C%7Ccbbb954e9e5d4b84649508d89778628a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637425890582985005%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=67zGFf%2BkjFQP3Wnh%2F2gr%2BF9o1AYY23Dm9yZOVxAl9r4%3D&reserved=0> ,

It might be better to handle this as an individual case. Because it doesn't seem like a core problem with the extension since I was unable to reproduce it. Could you contact us through support@tig.nl<mailto:support@tig.nl>? We will look into it specifically for your environment. I'll close this one once you agree on try the solve the case like that.

Kind regards,
Jasper
TIG

**Comment by tig-jeffreybranderhorst** [comment] 2021-03-03 12:47
Hi @albundy2 ,

It is been a while and I don't see your issue open anymore. So I will also close this issue on github. But if you ever need help don't hesitate to contact us at support@tig.nl! 

Have a great day,
Jeffrey

**Closed** 2021-03-03 12:47 UTC
Labels: can't reproduce

**Comment by jghaanstra** [comment] 2021-06-06 06:49
I have the same issue. Did you ever get this resolved @albundy2 ?

It seems to be related to using Amasty One Step Checkout extension.

**Comment by albundy2** [comment] 2021-06-06 11:02
I have change from Amasty One step checkout back to normal checkout magento 2 because of more issues.

Regards
Marcel

Van: Jelger Haanstra ***@***.***>
Verzonden: zondag 6 juni 2021 08:50
Aan: tig-nl/gls-magento2 ***@***.***>
CC: albundy2 ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tig-nl/gls-magento2] [BUG] Trying to get property 'deliveryAddress' of non-object (#9)


I have the same issue. Did you ever get this resolved @albundy2<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Falbundy2&data=04%7C01%7C%7C7649ba25541247c2feb008d928b74bda%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637585589975274397%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JlGYg2PJJ9M9OHv7ixPmj0jPgpuBm7CDfsSAeLwNyQw%3D&reserved=0> ?

It seems to be related to using Amasty One Step Checkout extension.

-
